scss_files: "src/assets/styles/scss/**/*.scss"
plugin_directories: ['.scss-linters']
severity: warning

linters:
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4
  StringQuotes:
    enabled: true
    style: double_quotes
  SingleLinePerSelector:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  PropertySortOrder:
    enabled: false

